### ISSUE TITLE
[Klett] Selectable Text throws error [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by allllo20** [RythenGlyth/EbookDownloader#23]
I installed everything as mentioned on the main page and everything works for klett except for selectable text. Whenever it is selected I receive this output:

> √ Password (Empty to read from config.json) ... ********
> √ Overwrite old temp files ... no
> √ Book » Arbeitsbücher Mathematik Oberstufe - Bundesausgabe ab 2018
> √ Selectable text ... off / on
> √ Hyperlinks ... off / on
> starting new downloader
> √ quality » 724 x 1024 (Scale 1)
> Deleted Temp files
> created Folder: ./out/DownloadTemp/Arbeitsbcher Mathematik Oberstufe - Bundesausgabe ab 2018_724x1024/
> Downloaded 20/20 pages
> Downloaded all images
> Downloading pages text
> Downloading selectable text positions (19/19)
> Merging into PDF
> RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5367866. Received 11701096
>     at boundsError (node:internal/buffer:88:9)
>     at Buffer.readInt16BE (node:internal/buffer:508:5)
>     at DecodeStream.<computed> [as readInt16BE] (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\DecodeStream.js:78:35)
>     at NumberT.decode (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\Number.js:18:36)
>     at Struct._parseFields (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\Struct.js:39:20)
>     at Struct.decode (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\Struct.js:10:10)
>     at $f71300a5bebbfea9$export$2e2bcd8739ae039._getCBox (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:10923:54)
>     at $f71300a5bebbfea9$export$2e2bcd8739ae039._getMetrics (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:11091:25)
>     at get advanceWidth (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:10787:21)
>     at descriptor.get (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:103:29) {
>   code: 'ERR_OUT_OF_RANGE'
> }
> arbeitsb�cher 55.64999999999998 76.06 314.77 63.53999999999999
> RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5367866. Received 11701096
>     at boundsError (node:internal/buffer:88:9)
>     at Buffer.readInt16BE (node:internal/buffer:508:5)
>     at DecodeStream.<computed> [as readInt16BE] (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\DecodeStream.js:78:35)
>     at NumberT.decode (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\Number.js:18:36)
>     at Struct._parseFields (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\Struct.js:39:20)
>     at Struct.decode (C:\Users\Ali\EbookDownloader-master\node_modules\restructure\src\Struct.js:10:10)
>     at $f71300a5bebbfea9$export$2e2bcd8739ae039._getCBox (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:10923:54)
>     at $f71300a5bebbfea9$export$2e2bcd8739ae039._getMetrics (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:11091:25)
>     at get advanceWidth (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:10787:21)
>     at descriptor.get (C:\Users\Ali\EbookDownloader-master\node_modules\fontkit\dist\main.cjs:103:29) {
>   code: 'ERR_OUT_OF_RANGE'
> }
> Error fetching pages

**Comment by RythenGlyth** [comment]
If you want you can send me your credentials via email ([my name]@gmail.com) and I can look into it.
